# Generated by Django 5.2.4 on 2025-08-04 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_instant', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_number', models.CharField(blank=True, help_text='Unique job identifier with prefix', max_length=20, null=True, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('bidding', 'Bidding in Progress'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('bidding_end_time', models.DateTimeField(blank=True, null=True)),
                ('minimum_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_vehicle_types', models.JSONField(blank=True, null=True)),
                ('required_qualifications', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'job',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('created', 'Job Created'), ('updated', 'Job Updated'), ('status_changed', 'Status Changed'), ('provider_assigned', 'Provider Assigned'), ('provider_accepted', 'Provider Accepted'), ('job_started', 'Job Started'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('document_uploaded', 'Document Uploaded'), ('message_sent', 'Message Sent'), ('payment_processed', 'Payment Processed'), ('rating_submitted', 'Rating Submitted'), ('system_notification', 'System Notification')], max_length=50)),
                ('description', models.TextField()),
                ('visibility', models.CharField(choices=[('all', 'Visible to All'), ('provider', 'Provider Only'), ('customer', 'Customer Only'), ('system', 'System Only')], default='all', max_length=20)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'db_table': 'timeline_event',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
