# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provider', '0003_initial'),
        ('ServiceRequest', '0002_initial'),
        ('Tracking', '0001_initial'),
        ('WasteBin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bintracking',
            name='smart_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='WasteBin.smartbin'),
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='ServiceRequest.servicerequest'),
        ),
        migrations.AddField(
            model_name='wastecollectiontracking',
            name='pickup_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tracking', to='ServiceRequest.servicerequest'),
        ),
        migrations.AddField(
            model_name='wastecollectiontracking',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_tracking', to='Provider.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='bintracking',
            index=models.Index(fields=['tracking_type'], name='bin_trackin_trackin_850885_idx'),
        ),
        migrations.AddIndex(
            model_name='bintracking',
            index=models.Index(fields=['smart_bin', 'created_at'], name='bin_trackin_smart_b_03dc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='bintracking',
            index=models.Index(fields=['fill_level'], name='bin_trackin_fill_le_ccaa07_idx'),
        ),
        migrations.AddIndex(
            model_name='bintracking',
            index=models.Index(fields=['maintenance_required'], name='bin_trackin_mainten_288443_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingupdate',
            index=models.Index(fields=['update_type'], name='tracking_up_update__c4a79e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingupdate',
            index=models.Index(fields=['created_at'], name='tracking_up_created_b2466c_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingupdate',
            index=models.Index(fields=['service_request', 'created_at'], name='tracking_up_service_1c3638_idx'),
        ),
        migrations.AddIndex(
            model_name='wastecollectiontracking',
            index=models.Index(fields=['stage'], name='waste_colle_stage_6b4d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='wastecollectiontracking',
            index=models.Index(fields=['pickup_request', 'created_at'], name='waste_colle_pickup__764a00_idx'),
        ),
        migrations.AddIndex(
            model_name='wastecollectiontracking',
            index=models.Index(fields=['provider', 'created_at'], name='waste_colle_provide_e40ba1_idx'),
        ),
    ]
