# Generated by Django 5.2.4 on 2025-08-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommonItems', '0001_initial'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitem',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Service category for this category of items', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.servicecategory'),
        ),
        migrations.AddField(
            model_name='commonitem',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CommonItems.itembrand'),
        ),
        migrations.AddField(
            model_name='itembrand',
            name='category',
            field=models.ForeignKey(help_text='Category this brand belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='CommonItems.itemcategory'),
        ),
        migrations.AddField(
            model_name='commonitem',
            name='category',
            field=models.ForeignKey(help_text='Category this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CommonItems.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='brand',
            field=models.ForeignKey(help_text='Brand this model belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='CommonItems.itembrand'),
        ),
        migrations.AddField(
            model_name='commonitem',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Model this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CommonItems.itemmodel'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='category',
            field=models.ForeignKey(help_text='Category this type belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='CommonItems.itemcategory'),
        ),
        migrations.AddField(
            model_name='itembrand',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type this brand belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='CommonItems.itemtype'),
        ),
        migrations.AddField(
            model_name='commonitem',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CommonItems.itemtype'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='vehicle_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehiclesize'),
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehicletype'),
        ),
        migrations.AlterUniqueTogether(
            name='itemmodel',
            unique_together={('name', 'brand')},
        ),
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='itembrand',
            unique_together={('name', 'category', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='commonitem',
            unique_together={('name', 'category', 'type', 'brand', 'model')},
        ),
    ]
