# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Contract", "0001_initial"),
        ("ServiceRequest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractagreement",
            name="logistics_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="ServiceRequest.servicerequest",
            ),
        ),
    ]
