# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payment', '0002_initial'),
        ('ServiceRequest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['event', 'processed'], name='payment_web_event_b8a5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['reference'], name='payment_web_referen_c4a4db_idx'),
        ),
        migrations.AddField(
            model_name='paystackcustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paystackpayment',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_payments', to='ServiceRequest.servicerequest'),
        ),
        migrations.AddField(
            model_name='paystackpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paystackpaymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paystackpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payment.paystackpaymentmethod'),
        ),
        migrations.AddField(
            model_name='transferrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='Payment.transferrecipient'),
        ),
        migrations.AddIndex(
            model_name='paystackpayment',
            index=models.Index(fields=['reference'], name='paystack_pa_referen_f7a0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackpayment',
            index=models.Index(fields=['status'], name='paystack_pa_status_1862b1_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackpayment',
            index=models.Index(fields=['user', '-created_at'], name='paystack_pa_user_id_02fb09_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['reference'], name='transfer_referen_76cd81_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='transfer_status_0f182e_idx'),
        ),
    ]
