# Generated by Django 5.2.5 on 2025-09-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteBin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='depth_cm',
            field=models.FloatField(default=60.0, help_text='Bin depth in centimeters'),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='height_cm',
            field=models.FloatField(default=100.0, help_text='Bin height in centimeters'),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='volume_liters',
            field=models.FloatField(blank=True, help_text='Calculated volume in liters', null=True),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='width_cm',
            field=models.FloatField(default=60.0, help_text='Bin width in centimeters'),
        ),
    ]
