# Generated by Django 5.2.5 on 2025-09-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WasteBin', '0002_smartbin_depth_cm_smartbin_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='sensor_data_updated',
            field=models.BooleanField(default=False, help_text='Flag to track sensor data updates'),
        ),
        migrations.AlterField(
            model_name='binalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
