# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provider', '0001_initial'),
        ('ServiceRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerearnings',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_records', to='ServiceRequest.servicerequest'),
        ),
    ]
