# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provider', '0002_initial'),
        ('Services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerearnings',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='serviceproviderthrough',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.services'),
        ),
        migrations.AddField(
            model_name='serviceproviderthrough',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='waste_categories',
            field=models.ManyToManyField(blank=True, related_name='providers', to='Provider.wastecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceproviderthrough',
            unique_together={('service_provider', 'service')},
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['verification_status'], name='service_pro_verific_e40c37_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['business_type'], name='service_pro_busines_530cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['waste_license_number'], name='service_pro_waste_l_3025cf_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_active', 'is_available'], name='service_pro_is_acti_7ca3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['base_location'], name='service_pro_base_lo_2267b6_idx'),
        ),
    ]
