# Generated by Django 5.2.5 on 2025-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
