# Generated by Django 5.2.5 on 2025-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0004_alter_serviceprovider_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='country',
            field=models.CharField(default='Ghana', max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='postcode',
            field=models.CharField(max_length=200),
        ),
    ]
