# Generated by Django 5.2.5 on 2025-09-01 13:24

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_initial'),
        ('Provider', '0005_alter_serviceprovider_country_and_more'),
        ('ServiceRequest', '0004_recyclingcenter_servicerequest_recycling_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route_name', models.CharField(help_text='Name/identifier for the route', max_length=255)),
                ('route_description', models.TextField(blank=True, help_text='Detailed description of the route')),
                ('route_type', models.CharField(choices=[('daily', 'Daily Route'), ('weekly', 'Weekly Route'), ('custom', 'Custom Route'), ('emergency', 'Emergency Route'), ('scheduled', 'Scheduled Route')], default='daily', max_length=20)),
                ('route_status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='planned', max_length=20)),
                ('start_location', django.contrib.gis.db.models.fields.PointField(help_text='Starting point of the route', srid=4326)),
                ('end_location', django.contrib.gis.db.models.fields.PointField(help_text='Ending point of the route', srid=4326)),
                ('waypoints', django.contrib.gis.db.models.fields.MultiPointField(blank=True, help_text='Intermediate points along the route', null=True, srid=4326)),
                ('route_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Total route distance in kilometers', max_digits=8, null=True)),
                ('route_duration_minutes', models.IntegerField(blank=True, help_text='Estimated route duration in minutes', null=True)),
                ('estimated_fuel_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated fuel cost for the route', max_digits=8, null=True)),
                ('scheduled_date', models.DateField(help_text='Date when route should be executed')),
                ('scheduled_start_time', models.TimeField(help_text='Scheduled start time')),
                ('scheduled_end_time', models.TimeField(help_text='Scheduled end time')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('pickup', 'Pickup Truck'), ('trailer', 'Trailer'), ('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle')], default='truck', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the route is currently active')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this route repeats')),
                ('recurrence_pattern', models.CharField(blank=True, help_text="Pattern for recurring routes (e.g., 'daily', 'weekly', 'monthly')", max_length=50)),
                ('route_instructions', models.TextField(blank=True, help_text='Special instructions for the route')),
                ('safety_notes', models.TextField(blank=True, help_text='Safety considerations and notes')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes specific to customers on this route')),
                ('total_stops', models.IntegerField(default=0, help_text='Total number of stops on the route')),
                ('completed_stops', models.IntegerField(default=0, help_text='Number of completed stops')),
                ('total_waste_collected', models.DecimalField(decimal_places=2, default=0, help_text='Total waste collected in kg', max_digits=10)),
                ('route_efficiency_score', models.DecimalField(blank=True, decimal_places=2, help_text='Efficiency score (0-100) based on completion time vs estimated time', max_digits=5, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated from this route', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost incurred for this route', max_digits=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing routes')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='Driver.driver')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_routes', to='Provider.serviceprovider')),
            ],
            options={
                'verbose_name': 'Pickup Route',
                'verbose_name_plural': 'Pickup Routes',
                'db_table': 'pickup_routes',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('optimization_type', models.CharField(choices=[('sequence', 'Stop Sequence Optimization'), ('timing', 'Timing Optimization'), ('vehicle', 'Vehicle Assignment'), ('driver', 'Driver Assignment'), ('fuel', 'Fuel Efficiency'), ('distance', 'Distance Reduction')], max_length=20)),
                ('suggested_changes', models.JSONField(help_text='JSON object containing suggested changes')),
                ('estimated_improvement', models.DecimalField(decimal_places=2, help_text='Estimated improvement percentage', max_digits=5)),
                ('is_applied', models.BooleanField(default=False, help_text='Whether the optimization was applied')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actual_improvement', models.DecimalField(blank=True, decimal_places=2, help_text='Actual improvement achieved after applying optimization', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the optimization')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_optimizations', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimizations', to='Provider.pickuproute')),
            ],
            options={
                'verbose_name': 'Route Optimization',
                'verbose_name_plural': 'Route Optimizations',
                'db_table': 'route_optimizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_order', models.IntegerField(help_text='Order of this stop in the route')),
                ('estimated_arrival_time', models.TimeField(help_text='Estimated time of arrival at this stop')),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('stop_duration_minutes', models.IntegerField(blank=True, help_text='Actual time spent at this stop', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('waste_collected_kg', models.DecimalField(decimal_places=2, default=0, help_text='Waste collected at this stop', max_digits=10)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, help_text='Revenue generated from this stop', max_digits=10)),
                ('stop_instructions', models.TextField(blank=True, help_text='Specific instructions for this stop')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes about the customer or location')),
                ('driver_notes', models.TextField(blank=True, help_text='Notes from the driver about this stop')),
                ('is_on_time', models.BooleanField(blank=True, help_text='Whether the stop was completed on time', null=True)),
                ('customer_satisfaction', models.IntegerField(blank=True, help_text='Customer satisfaction rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='Provider.pickuproute')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='ServiceRequest.servicerequest')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'db_table': 'route_stops',
                'ordering': ['route', 'stop_order'],
            },
        ),
        migrations.AddIndex(
            model_name='pickuproute',
            index=models.Index(fields=['provider', 'scheduled_date'], name='pickup_rout_provide_654c45_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuproute',
            index=models.Index(fields=['route_status', 'is_active'], name='pickup_rout_route_s_17e70f_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuproute',
            index=models.Index(fields=['assigned_driver', 'scheduled_date'], name='pickup_rout_assigne_88ca5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'stop_order')},
        ),
    ]
