# Generated by Django 5.2.5 on 2025-09-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0006_pickuproute_routeoptimization_routestop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='base_location_address',
            field=models.CharField(blank=True, help_text='Human-readable address of base location', max_length=500),
        ),
    ]
