# Generated by Django 5.2.5 on 2025-09-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_initial'),
        ('Provider', '0007_add_base_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerearnings',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_earnings', to='Payment.payment'),
        ),
    ]
