# Generated by Django 5.2.5 on 2025-09-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0002_add_current_location_fields'),
        ('Provider', '0008_providerearnings_payment'),
    ]

    operations = [
    ]
