# Generated by Django 5.2.5 on 2025-08-24 22:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceRequest', '0003_alter_servicerequest_estimated_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('campaign_type', models.CharField(choices=[('challenge', 'Recycling Challenge'), ('achievement', 'Achievement'), ('referral', 'Referral Program'), ('loyalty', 'Loyalty Program'), ('seasonal', 'Seasonal Campaign'), ('awareness', 'Awareness Campaign')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('customers', 'Customers Only'), ('providers', 'Providers Only'), ('new_users', 'New Users'), ('inactive_users', 'Inactive Users')], default='all', max_length=20)),
                ('target_regions', models.JSONField(blank=True, default=list)),
                ('target_user_types', models.JSONField(blank=True, default=list)),
                ('progress', models.PositiveIntegerField(default=0, help_text='Current progress towards target')),
                ('target', models.PositiveIntegerField(default=100, help_text='Target goal to achieve')),
                ('reward', models.PositiveIntegerField(default=0, help_text='Reward points or amount')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('campaign_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('auto_generate_code', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('requires_signup', models.BooleanField(default=False)),
                ('terms_conditions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_discounts_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Campaign.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign analytics',
            },
        ),
        migrations.CreateModel(
            name='CampaignUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='Campaign.campaign')),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ServiceRequest.servicerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
