version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=morevans_db
      - DB_USER=morevans_user
      - DB_PASSWORD=morevans_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=morevans_db
      - POSTGRES_USER=morevans_user
      - POSTGRES_PASSWORD=morevans_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
