# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Notification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='notificatio_user_id_d59197_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f8d066_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_86bdfc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_f83d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['thread_id'], name='notificatio_thread__29ee57_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['waste_type'], name='notificatio_waste_t_8387ec_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['bin_id'], name='notificatio_bin_id_c25028_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['urgency_level'], name='notificatio_urgency_881363_idx'),
        ),
    ]
