# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0002_initial'),
        ('Provider', '0003_initial'),
        ('ServiceRequest', '0001_initial'),
        ('WasteBin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenreport',
            name='smart_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_reports', to='WasteBin.smartbin'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to='Driver.driver'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='offered_provider',
            field=models.ForeignKey(blank=True, help_text='Provider who was offered this service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_service_requests', to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='smart_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='WasteBin.smartbin'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequesttimelineevent',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='ServiceRequest.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequesttimelineevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['report_type'], name='citizen_rep_report__84f225_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['status'], name='citizen_rep_status_7c4f76_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['priority'], name='citizen_rep_priorit_13176a_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['reporter_user'], name='citizen_rep_reporte_85cf80_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenreport',
            index=models.Index(fields=['smart_bin'], name='citizen_rep_smart_b_639121_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['service_type'], name='service_req_service_07565e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='service_req_status_ba17eb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['priority'], name='service_req_priorit_c7edb9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['user', '-created_at'], name='service_req_user_id_68e480_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_provider', 'status'], name='service_req_assigne_849439_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['waste_type'], name='service_req_waste_t_eacf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['is_instant'], name='service_req_is_inst_f4909a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['service_date'], name='service_req_service_e704c8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequesttimelineevent',
            index=models.Index(fields=['service_request', 'event_type'], name='service_req_service_ad850a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequesttimelineevent',
            index=models.Index(fields=['timestamp'], name='service_req_timesta_004426_idx'),
        ),
    ]
