# Generated by Django 5.2.5 on 2025-08-24 15:08

import django.contrib.gis.db.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='pickup_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates for pickup', null=True, srid=4326),
        ),
    ]
