# Generated by Django 5.2.5 on 2025-08-25 00:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceRequest', '0003_alter_servicerequest_estimated_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('operating_hours', models.CharField(max_length=255)),
                ('accepted_materials', models.JSONField(default=list)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_utilization', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True)),
            ],
            options={
                'verbose_name': 'Recycling Center',
                'verbose_name_plural': 'Recycling Centers',
                'db_table': 'recycling_centers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='recycling_c_status_24d00e_idx'), models.Index(fields=['city'], name='recycling_c_city_8e69fd_idx'), models.Index(fields=['state'], name='recycling_c_state_a3498b_idx')],
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='recycling_center',
            field=models.ForeignKey(blank=True, help_text='Recycling center for recycling service requests', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='ServiceRequest.recyclingcenter'),
        ),
    ]
