# Generated by Django 5.2.5 on 2025-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Provider", "0006_pickuproute_routeoptimization_routestop_and_more"),
        ("ServiceRequest", "0004_recyclingcenter_servicerequest_recycling_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="offered_providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Providers who were offered this service",
                related_name="offered_service_requests",
                to="Provider.serviceprovider",
            ),
        ),
    ]
