# Generated by Django 5.2.5 on 2025-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Provider", "0006_pickuproute_routeoptimization_routestop_and_more"),
        ("ServiceRequest", "0005_add_offered_providers_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="accepted_providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Providers who accepted the offer for this service",
                related_name="accepted_service_requests",
                to="Provider.serviceprovider",
            ),
        ),
    ]
