# Generated by Django 5.2.5 on 2025-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Provider", "0006_pickuproute_routeoptimization_routestop_and_more"),
        ("ServiceRequest", "0006_add_accepted_providers_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="declined_providers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Providers who declined the offer for this service",
                related_name="declined_service_requests",
                to="Provider.serviceprovider",
            ),
        ),
    ]
