# Generated by Django 5.2.5 on 2025-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Provider", "0006_pickuproute_routeoptimization_routestop_and_more"),
        ("ServiceRequest", "0007_add_declined_providers_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="requested_to_be_offered",
            field=models.ManyToManyField(
                blank=True,
                help_text="Providers who requested to be offered this service",
                related_name="requested_offer_service_requests",
                to="Provider.serviceprovider",
            ),
        ),
    ]
