# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('stop', 'Intermediate Stop')], max_length=20)),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('floor', models.IntegerField(default=0)),
                ('has_elevator', models.BooleanField(default=False)),
                ('parking_info', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('completed_time', models.TimeField(blank=True, null=True)),
                ('property_type', models.CharField(default='house', max_length=50)),
                ('number_of_rooms', models.IntegerField(blank=True, default=1, null=True)),
                ('number_of_floors', models.IntegerField(blank=True, default=1, null=True)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='Location.location')),
            ],
            options={
                'verbose_name': 'Journey Stop',
                'verbose_name_plural': 'Journey Stops',
                'db_table': 'journey_stop',
                'ordering': ['sequence'],
                'managed': True,
            },
        ),
    ]
