# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JourneyStop', '0001_initial'),
        ('ServiceRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystop',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='ServiceRequest.servicerequest'),
        ),
    ]
