# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Driver', '0001_initial'),
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='provider',
            field=models.ForeignKey(help_text='Service provider this driver works for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='driverinfringement',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infringements', to='Driver.driver'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.driver'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['provider'], name='driver_provide_c9ef91_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status'], name='driver_status_8b0d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_expiry_date'], name='driver_license_2754db_idx'),
        ),
    ]
