# Generated by Django 5.2.4 on 2025-08-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_text',
            field=models.CharField(blank=True, help_text='Text for action button', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL for notification action', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_channels',
            field=models.JSONField(default=list, help_text='List of channels to deliver notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When notification expires', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Schedule notification for later', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('request_update', 'Request Status Update'), ('provider_accepted', 'Provider Accepted Job'), ('provider_assigned', 'Provider Assigned'), ('job_started', 'Job Started'), ('job_in_transit', 'Job In Transit'), ('job_completed', 'Job Completed'), ('job_cancelled', 'Job Cancelled'), ('account_verified', 'Account Verified'), ('provider_verified', 'Provider Account Verified'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('deposit_received', 'Deposit Received'), ('bid_received', 'New Bid Received'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_counter_offer', 'Counter Offer Made'), ('message_received', 'New Message'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_updated', 'Support Ticket Updated'), ('review_received', 'New Review Received'), ('rating_reminder', 'Rating Reminder'), ('system_maintenance', 'System Maintenance'), ('policy_update', 'Policy Update'), ('feature_announcement', 'New Feature'), ('account_warning', 'Account Warning'), ('payment', 'Payment Notification'), ('bid', 'Bid Notification'), ('message', 'New Message'), ('system', 'System Notification')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
