# Generated by Django 5.2.4 on 2025-08-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_notification_action_text_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('request_update', 'Request Status Update'), ('provider_accepted', 'Provider Accepted Job'), ('provider_assigned', 'Provider Assigned'), ('job_started', 'Job Started'), ('job_in_transit', 'Job In Transit'), ('job_completed', 'Job Completed'), ('job_cancelled', 'Job Cancelled'), ('account_verified', 'Account Verified'), ('provider_verified', 'Provider Account Verified'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('deposit_received', 'Deposit Received'), ('bid_received', 'New Bid Received'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_counter_offer', 'Counter Offer Made'), ('message_received', 'New Message'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_updated', 'Support Ticket Updated'), ('review_received', 'New Review Received'), ('rating_reminder', 'Rating Reminder'), ('system_maintenance', 'System Maintenance'), ('policy_update', 'Policy Update'), ('feature_announcement', 'New Feature'), ('account_warning', 'Account Warning'), ('system_test', 'System Test'), ('payment', 'Payment Notification'), ('bid', 'Bid Notification'), ('message', 'New Message'), ('system', 'System Notification')], max_length=30),
        ),
    ]
