# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommonItems', '0002_initial'),
        ('JourneyStop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Unnamed Item', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.JSONField(blank=True, null=True)),
                ('fragile', models.BooleanField(default=False)),
                ('needs_disassembly', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CommonItems.itemcategory')),
                ('dropoff_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_items', to='JourneyStop.journeystop')),
                ('pickup_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_items', to='JourneyStop.journeystop')),
            ],
            options={
                'verbose_name': 'ServiceRequest Item',
                'verbose_name_plural': 'ServiceRequest Items',
                'db_table': 'request_item',
                'managed': True,
            },
        ),
    ]
