# Generated by Django 5.2.4 on 2025-08-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bidding', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Bid', 'verbose_name_plural': 'Bids'},
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='notes',
            new_name='message',
        ),
    ]
