# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommonItems', '0001_initial'),
        ('Driver', '0001_initial'),
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.CharField(help_text='UK Vehicle Registration Number (e.g., AB12 CDE, WK20 ABC, YK23 XYZ)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9 ]{1,10}$', 'Valid UK vehicle registration required')])),
                ('make', models.CharField(help_text='Vehicle manufacturer', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Year of manufacture', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2030)])),
                ('seats', models.IntegerField(default=2)),
                ('vehicle_category_enhanced', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('truck', 'Truck'), ('waste_collection', 'Waste Collection Vehicle'), ('recycling_truck', 'Recycling Truck'), ('skip_loader', 'Skip Loader'), ('compactor', 'Waste Compactor'), ('bulk_hauler', 'Bulk Waste Hauler')], default='van', max_length=20)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('plugin_hybrid', 'Plug-in Hybrid'), ('hydrogen', 'Hydrogen'), ('lpg', 'LPG'), ('cng', 'CNG')], max_length=15)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('payload_capacity_kg', models.PositiveIntegerField(help_text='Maximum payload in kg')),
                ('gross_vehicle_weight_kg', models.PositiveIntegerField(help_text='Gross vehicle weight in kg (GVW)')),
                ('max_length_m', models.IntegerField(blank=True, null=True)),
                ('load_volume_m3', models.DecimalField(decimal_places=2, help_text='Load volume in cubic meters', max_digits=5)),
                ('waste_types_handled', models.JSONField(blank=True, default=list, help_text='Types of waste this vehicle can handle')),
                ('has_compaction_system', models.BooleanField(default=False, help_text='Vehicle has waste compaction system')),
                ('compaction_ratio', models.DecimalField(blank=True, decimal_places=1, help_text='Compaction ratio (e.g., 3:1 means 3x volume reduction)', max_digits=3, null=True)),
                ('has_lift_system', models.BooleanField(default=False, help_text='Vehicle has lift system for bins')),
                ('bin_capacity_count', models.IntegerField(blank=True, help_text='Number of bins vehicle can carry simultaneously', null=True)),
                ('collection_method', models.CharField(choices=[('manual', 'Manual Collection'), ('automated', 'Automated Lift'), ('side_loader', 'Side Loader'), ('rear_loader', 'Rear Loader'), ('front_loader', 'Front Loader')], default='manual', max_length=20)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('has_tail_lift', models.BooleanField(default=False)),
                ('has_tracking_device', models.BooleanField(default=False)),
                ('has_dash_cam', models.BooleanField(default=False)),
                ('has_gps_tracking', models.BooleanField(default=True, help_text='Vehicle has GPS tracking')),
                ('has_route_optimization', models.BooleanField(default=False, help_text='Vehicle supports route optimization')),
                ('additional_features', models.JSONField(blank=True, help_text='Additional vehicle features', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Vehicle is currently active in the fleet')),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Current GPS location of the vehicle', null=True, srid=4326)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('primary_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Primary location where this vehicle is based', null=True, srid=4326)),
                ('service_area', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geographic service area for this vehicle', null=True, srid=4326)),
                ('location', models.JSONField(blank=True, help_text='Last known location (legacy)', null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Vehicle is available for jobs')),
                ('current_waste_load_kg', models.DecimalField(decimal_places=2, default=0, help_text='Current waste load in kg', max_digits=8)),
                ('current_waste_load_percentage', models.IntegerField(default=0, help_text='Current waste load as percentage of capacity', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_collection_time', models.DateTimeField(blank=True, null=True)),
                ('next_scheduled_collection', models.DateTimeField(blank=True, null=True)),
                ('primary_driver', models.ForeignKey(blank=True, help_text='Driver primarily assigned to this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_vehicles', to='Driver.driver')),
                ('provider', models.ForeignKey(help_text='Service provider that owns this vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='provider_vehicles', to='Provider.serviceprovider')),
                ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehiclecategory')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
                'ordering': ['provider', 'registration'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vehicle_photos/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the photo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (1-5)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Photo',
                'verbose_name_plural': 'Vehicle Photos',
                'db_table': 'vehicle_images',
                'ordering': ['vehicle', 'order', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Service'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('emergency', 'Emergency Repair'), ('waste_system', 'Waste System Maintenance')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_date', models.DateField()),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('mileage_at_service', models.IntegerField(blank=True, null=True)),
                ('service_provider', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='Vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Maintenance',
                'verbose_name_plural': 'Vehicle Maintenance Records',
                'db_table': 'vehicle_maintenance',
                'ordering': ['-service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration'], name='vehicle_registr_a8749d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['provider'], name='vehicle_provide_4904c7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicle_vehicle_24f066_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_category_enhanced'], name='vehicle_vehicle_3f1702_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active', 'is_available'], name='vehicle_is_acti_004929_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['collection_method'], name='vehicle_collect_f9f50a_idx'),
        ),
    ]
