# Generated by Django 5.2.4 on 2025-08-04 23:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(blank=True, help_text='CSS color classes', max_length=50)),
                ('tab_color', models.CharField(blank=True, help_text='CSS color classes for tabs', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'db_table': 'service_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(blank=True, help_text='CSS color classes', max_length=50)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Estimated duration in hours', null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Base price for the service', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('providers', models.ManyToManyField(through='Provider.ServiceProviderThrough', to='Provider.serviceprovider')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'managed': True,
            },
        ),
    ]
