name: wastewise_mobile
description: WasteWise - Smart Waste Management Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  
  # Navigation & Routing
  get: ^4.6.6
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  animations: ^2.0.11
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  
  # API & Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Authentication
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Image & File Handling
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  flutter_image_compress: ^2.1.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  
  # Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  
  # Payment
  flutter_paystack: ^1.0.7
  pay: ^2.0.0
  
  # Utilities
  intl: ^0.18.1
  timeago: ^3.6.0
  url_launcher: ^6.2.3
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.2.0
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^24.1.44
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Animations & Effects
  lottie: ^3.0.0
  flutter_animate: ^4.3.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.ttf
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700