# Generated by Django 5.2.4 on 2025-08-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JourneyStop', '0001_initial'),
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystop',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='Request.request'),
        ),
    ]
