# Generated by Django 5.2.4 on 2025-08-13 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint_hash', models.CharField(max_length=256)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_sessions',
                'indexes': [models.Index(fields=['user', 'otp_expires_at'], name='login_sessi_user_id_549e6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=128)),
                ('device_fingerprint_hash', models.CharField(max_length=256)),
                ('device_name', models.CharField(blank=True, max_length=200)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('refresh_token_hash', models.CharField(blank=True, max_length=256)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_devices',
                'indexes': [models.Index(fields=['user', 'device_id'], name='trusted_dev_user_id_a23b33_idx'), models.Index(fields=['user', 'device_fingerprint_hash'], name='trusted_dev_user_id_f6b2f3_idx'), models.Index(fields=['refresh_token_hash'], name='trusted_dev_refresh_6f302b_idx'), models.Index(fields=['expires_at'], name='trusted_dev_expires_cd22b8_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
