# Generated by Django 5.2.4 on 2025-08-04 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_coverage', models.DecimalField(decimal_places=2, help_text='Insurance value', max_digits=10)),
                ('cancellation_policy', models.JSONField(help_text='Cancellation and refund terms')),
                ('customer_signed', models.BooleanField(default=False)),
                ('provider_signed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signatures'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement_start_date', models.DateTimeField(null=True)),
                ('agreement_end_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'contract_agreement',
                'managed': True,
            },
        ),
    ]
