# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('punctuality_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('service_quality_rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('rating_type', models.CharField(choices=[('service', 'Service Rating'), ('provider', 'Provider Rating'), ('shipment', 'Shipment Rating'), ('job', 'ServiceRequest Rating'), ('waste_collection', 'Waste Collection Rating')], max_length=20)),
                ('overall_rating', models.DecimalField(decimal_places=2, help_text='Overall rating from 1.0 to 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('punctuality_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Punctuality rating from 1.0 to 5.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('professionalism_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Professionalism rating from 1.0 to 5.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('service_quality_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Service quality rating from 1.0 to 5.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('communication_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Communication rating from 1.0 to 5.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('value_for_money_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Value for money rating from 1.0 to 5.0', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_text', models.TextField(blank=True, help_text='Detailed review text')),
                ('would_recommend', models.BooleanField(default=True, help_text='Would recommend to others')),
                ('response_text', models.TextField(blank=True, help_text='Response from the rated entity')),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this rating is verified')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Whether this is an anonymous rating')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
