# Generated by Django 5.2.5 on 2025-08-24 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contract', '0002_initial'),
        ('Review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Contract.contractagreement'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating_type'], name='ratings_rating__ee5a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['overall_rating'], name='ratings_overall_2448fc_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['content_type', 'object_id'], name='ratings_content_829faf_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rater'], name='ratings_rater_i_8e9aab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('content_type', 'object_id', 'rater', 'rating_type')},
        ),
    ]
